spring.data.mongodb.uri=mongodb+srv://admin:Binu1234@cluster0.geyjvta.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smartcampus
spring.data.mongodb.auto-index-creation=true