spring.application.name=booking-system
# spring.data.mongodb.uri=mongodb+srv://admin:12345@cluster0.rzmvegs.mongodb.net/booking_db
spring.data.mongodb.uri=mongodb+srv://admin:12345@cluster0.rzmvegs.mongodb.net/booking_db?retryWrites=true&w=majority&authSource=admin
server.port=8080
