spring.data.mongodb.uri=mongodb+srv://admin:Binu1234@cluster0.geyjvta.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smartcampus
spring.data.mongodb.auto-index-creation=true

# file upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB