spring.application.name=booking-system
# spring.data.mongodb.uri=mongodb+srv://admin:12345@cluster0.rzmvegs.mongodb.net/booking_db
spring.data.mongodb.uri=mongodb+srv://admin:12345@cluster0.rzmvegs.mongodb.net/booking_db?retryWrites=true&w=majority&authSource=admin
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pawanisanjana69@gmail.com
spring.mail.password=wjjk vrjk igtq mfkr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true